### ISSUE TITLE
Multiprocessing error running optimize_parallel_gpu with pytorch + pytorch-lightning

### ISSUE THREAD

**Issue by jtamir** [williamFalcon/test-tube#56]
I am following the guide to optimize hyperparameters over multiple GPUs: https://towardsdatascience.com/trivial-multi-node-training-with-pytorch-lightning-ff75dfb809bd

However, when I run the hyperparam opt, I get the following error: 
```
RuntimeError: cuda runtime error (3) : initialization error at /pytorch/aten/src/THC/THCGeneral.cpp:54
```

Based on some reading, it seems to be an issue with initializing CUDA and multiprocessing, with the suggested change of adding `multiprocessing.set_start_method('spawn', force=True)`.

Looking at `argparse_hopt.py`, I see that that specific line is commented out. When I uncomment it, I get through that error but hit a pickle error:
```
AttributeError: Can't pickle local object 'HyperOptArgumentParser.optimize_parallel_gpu.<locals>.init'
```

Looking for suggestions on what to try, thanks!

**Comment by falceeffect** [comment]
Also having this one

**Comment by williamFalcon** [comment]
I might need to update that post, but run these demos instead:

https://github.com/williamFalcon/pytorch-lightning/tree/master/examples/multi_node_examples

**Comment by williamFalcon** [comment]
could you post your code and error?

**Comment by falceeffect** [comment]
I'm kind of looking for a way to evaluate each set of hyperparams on a separate GPU in parallel, not train a single model on multiple GPUs. I've tried this:
```python
def train_one(hparam, gpu_id_set):
    # load data, create model, create logger and checkpoint callback
    trainer = Trainer(logger=tt_logger, checkpoint_callback=checkpoint_callback,
                      gpus=[int(gpu_id_set)], max_nb_epochs=hparam.epochs, weights_summary=None)
    trainer.fit(model)
    trainer.test(model)

hparams.optimize_parallel_gpu(train_one, max_nb_trials=400, gpu_ids=gpu_ids)
```

**Comment by BraveDistribution** [comment]
Any help? Having similar issue but without multi-node (I have two GPUs in my PC).

**Comment by jtamir** [comment]
I was able to get this working, though I can't remember exactly all the steps. My code is available here: https://github.com/jtamir/deepinpy/blob/master/main.py#L113

Things I remember being important:
- Set num_workers=0 in your DataLoader or Python will try to spawn multiple Multiprocessing pools
- Always pass GPU ID 0 to Pytorch Lightning's trainer, because TestTube already handles the GPU IDs: https://github.com/jtamir/deepinpy/blob/master/main.py#L46
- Set distributed_backend=None in the trainer for similar reasons

**Comment by BraveDistribution** [comment]
@jtamir 

Thank you for your quick response. I was lucky and I solved this myself even sooner.  

You did mention everything except one thing. In testtube I had to remove the nested functions in (when pool is creating new processes) because pickle can't handle that. This removed the error: AttributeError: Can't pickle local object 'HyperOptArgumentParser.optimize_parallel_gpu.<locals>.init'

after that I did all your steps and it works!

Maybe I will write a blog post about that or something... Also we should make a pull request for testtube (I will look into it...).

**Comment by yang-xidian** [comment]
use torch=1.13.0 pytorch-lighting=1.0.8 output:
File "/home/xiaoyang/python/envs/taming/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LightningDistributedDataParallel' object has no attribute '_sync_params'
